Added parent child resolvers
Ensembl/ensembl-hypsipyle pull request #22
Opened 2023-11-03 12:26 UTC by likhitha-surapaneni

Ticket: [ENSVAR-6050](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6050)

2023-11-06 17:46 UTC, nakib103 requested changes

2023-11-06 17:46 UTC, nakib103 commented on common/file_model/variant_allele.py
> +        self.info_map = self.traverse_csq_info()
Should we be creating the full map all at once here?
Currently it fails to retrieve any allele field even if one of those that rely on this map fails, for example `Polyphen` in yeast.

2023-11-06 17:46 UTC, nakib103 commented on common/file_model/variant_allele.py
> +        allele_index = self.variant.get_info_key_index("Allele")
Some of this field is not guaranteed to be in the data file, for example - `Conservation` or `CADD` or `Feature`. It depends on the species and type of variants (e.g - `intergenic`). We should not break a api if a field or value is missing, rather return null or empty value depending on the schema.

2023-11-08 09:53 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +        self.info_map = self.traverse_csq_info()
Working on this in [ENSVAR-6050](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6050)

2023-11-08 09:54 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +        allele_index = self.variant.get_info_key_index("Allele")
Thanks you @nakib103 , working on this in [ENSVAR-6050](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6050)

2023-11-08 10:24 UTC, nakib103 approved these changes
Great, thanks Likhitha!

2023-11-08 14:33 UTC, merged