Support primary_source and phenotypes fields in v110
Ensembl/ensembl-hypsipyle pull request #23
Opened 2023-11-08 14:43 UTC by likhitha-surapaneni

[ENSVAR-6050](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6050)

2023-11-23 11:14 UTC, nakib103 requested changes

2023-11-23 11:14 UTC, nakib103 commented on common/file_model/variant_allele.py
> +                    "accession_id": feature_type
we have the feature type in the phenotype value,  e.g -
`ANGIOTENSINOGEN+MIM_morbid+ENSG00000135744` or
`RENAL_TUBULAR_DYSGENESIS+ClinVar+rs699`

It can be gene, variant etc not always transcript. we should take the `feature` from there if available I think. We can try to determine the the `feature_type` from the `feature`.

2023-11-23 11:14 UTC, nakib103 commented on common/file_model/variant_allele.py
> +                "evidence": []
We have the source information - can we add that to evidence?

2023-11-23 11:14 UTC, nakib103 commented on common/file_model/variant_allele.py
> +        return
this `return` seem redundant.
```suggestion
```

2023-11-23 12:05 UTC, nakib103 requested changes

2023-11-23 12:05 UTC, nakib103 commented on common/file_model/variant_allele.py
> +            if "allele" not in info_map.keys():
it should be -
```suggestion
            if csq_record_list[prediction_index_map["allele"]] not in info_map.keys():
```

2023-11-23 12:08 UTC, nakib103 requested changes

2023-11-23 12:08 UTC, nakib103 commented on common/file_model/variant_allele.py
> +            prediction_results = self.create_allele_prediction_results([], csq_record_list, prediction_index_map)
it should not be empty array as current prediction results rather the prediction result accumulated. Otherwise we create a lot of duplicate CADD and GERP scores - adding same score for different transcripts.

2023-11-27 10:31 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +                "evidence": []
Populated some fields within evidence. Kindly let me know if needs improvement

2023-11-27 10:32 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +            prediction_results = self.create_allele_prediction_results([], csq_record_list, prediction_index_map)
Agreed, fixed this. Also added ancestral allele and shifted GERP to variant level

2023-11-27 10:32 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +                    "accession_id": feature_type
Agreed, parsing `feature` and `feature_type` from phenotypes column

2023-11-28 12:21 UTC, nakib103 requested changes

2023-11-28 12:21 UTC, nakib103 commented on common/file_model/variant_allele.py
> +        if re.search("^rs", feature):
would not it better to have `if-elif` structure?

2023-11-28 12:21 UTC, nakib103 commented on common/file_model/variant_allele.py
> +            feature_type = "Variant"
we should account for when `feature_type` do not fall into either of these three. `OntologyTermMetadata` allow nullable field for all of its element. Can we keep it `null` if such scenario arises?

2023-11-28 12:21 UTC, nakib103 commented on common/file_model/variant_allele.py
> +            prediction_results = self.create_allele_prediction_results([], csq_record_list, prediction_index_map)
Thanks, I can see `AA` should be on variant level too according to VDM - 
https://github.com/Ensembl/ensembl-vdm-docs/blob/main/src/docs/variant.md

2023-11-28 12:31 UTC, nakib103 requested changes

2023-11-28 12:31 UTC, nakib103 commented on common/file_model/variant_allele.py
> +            phenotypes = csq_record_list[prediction_index_map["phenotypes"]].split("&") if "phenotypes" in prediction_index_map.keys() else []
should we put this before line 63 for improved readability and structure?

2023-11-28 12:31 UTC, nakib103 commented on common/file_model/variant_allele.py
> +                info_map[csq_record_list[prediction_index_map["allele"]]]["prediction_results"] += self.create_allele_prediction_results(prediction_results, csq_record_list, prediction_index_map)
- line 70: This will create `KeyError` if no `prediction_results` is present in the object.
- line 71: no object called `prediction_results` defined before.

2023-11-28 12:44 UTC, nakib103 requested changes

2023-11-28 12:44 UTC, nakib103 commented on common/file_model/variant_allele.py
> +            evidence =  {
It seems `assertion` is non-nullable field in evidence. We do not have this information currently in the data files. Is it alright to keep this element empty here?

2023-11-28 12:59 UTC, nakib103 requested changes

2023-11-28 12:59 UTC, nakib103 commented on common/file_model/variant_allele.py
> +                info_map[csq_record_list[prediction_index_map["allele"]]]["prediction_results"] += self.create_allele_prediction_results(prediction_results, csq_record_list, prediction_index_map)
It will only get one `prediction_results` (from the `else` statement). Once because we will not enter into `else` statement after we get non-empty `prediction_results` from `create_allele_prediction_results` function.

2023-11-28 13:02 UTC, nakib103 requested changes

2023-11-28 13:02 UTC, nakib103 commented on common/file_model/variant_allele.py
> +                        "result": csq_record[prediction_index_map["cadd_phred"]] ,
We need account for empty value here.

2023-11-28 13:02 UTC, nakib103 commented on common/file_model/variant_allele.py
> +                        "result": csq_record[prediction_index_map["aa"]] ,
same - account for empty value.

2023-11-28 13:02 UTC, nakib103 commented on common/file_model/variant.py
> +                    "result": csq_record_list[gerp_index] ,
same - account for empty value

2023-11-29 09:51 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +            evidence =  {
Hi @nakib103 , I am reconsidering populating evidence, should we do it in the next stage when we have assertion data?

2023-11-29 10:23 UTC, nakib103 requested changes

2023-11-29 10:23 UTC, nakib103 commented on common/file_model/variant_allele.py
> +                info_map[csq_record_list[prediction_index_map["allele"]]]["prediction_results"] += self.create_allele_prediction_results(prediction_results, csq_record_list, prediction_index_map)
```suggestion
            current_prediction_results = info_map[csq_record_list[prediction_index_map["allele"]]]["prediction_results"]
            info_map[csq_record_list[prediction_index_map["allele"]]]["prediction_results"] += self.create_allele_prediction_results(current_prediction_results, csq_record_list, prediction_index_map)
```

and delete the `else` . See if it makes sense.

2023-11-29 14:06 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +                info_map[csq_record_list[prediction_index_map["allele"]]]["prediction_results"] += self.create_allele_prediction_results(prediction_results, csq_record_list, prediction_index_map)
I think it makes sense now, corrected this

2023-11-29 14:15 UTC, likhitha-surapaneni commented on common/file_model/variant.py
> +        self.vep_version = source = self.header.get_lines("VEP")[0].value
Hardcoded it for now, creating a ticket to look into how to fetch data regarding release in the longer term

2023-11-29 15:38 UTC, nakib103 requested changes

2023-11-29 16:18 UTC, nakib103 approved these changes
Looks good, thanks Likhitha!

2023-11-29 16:20 UTC, merged