Support primary_source
Ensembl/ensembl-hypsipyle pull request #25
Opened 2023-11-15 13:42 UTC by likhitha-surapaneni

API fetched primary_source from the header previously. Modified logic to check from INFO column first and then fallback to fetching from the header.

2023-11-15 13:49 UTC, nakib103 requested changes

2023-11-15 13:49 UTC, nakib103 commented on common/file_model/variant.py
> +                source_release = ""
We can also have "Ensembl" source

2023-11-15 13:49 UTC, nakib103 commented on common/file_model/variant.py
>              return None
If we cannot get any of them should we send None, primary_source being non-nullable.
`primary_source: ExternalReference!`

Maybe we can say something like `Unknown` or `Undeterminable`.

2023-11-15 14:00 UTC, nakib103 requested changes

2023-11-15 14:00 UTC, nakib103 commented on common/file_model/variant.py
> +
The DbSNP release is now `156`

2023-11-15 14:38 UTC, likhitha-surapaneni commented on common/file_model/variant.py
>              return None
Currently, we are sending None as part of error handling forcing the api to fail when the source is not in the expected format. I agree. We should also handle sources other than dbSNP, EVA and Ensembl.

2023-11-17 14:58 UTC, nakib103 approved these changes
Looks Good!~

2023-11-17 15:10 UTC, merged