Format source payload using data from data-file
Ensembl/ensembl-hypsipyle pull request #28
Opened 2024-01-15 12:12 UTC by nakib103

[ENSVAR-6163](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6163)
https://github.com/Ensembl/ensembl-hypsipyle/issues/27

- get source information from data-file and format accordingly (details on the above issue).
- create payload from the source information obtained from data-file; otherwise fall-back to default value for main accessioning resource.
- source information obtained from data-file is cached.

### Test
```
query yeast_source {
  variant(
    by_id: {genome_id: "a733574a-93e7-11ec-a39d-005056b38ce3", variant_id: "I:84:s01-84"}
  ) {
    name
    primary_source {
      description
      url
      source {
        name
        url
        release
      }
    }
  }
}
```

vitis_vinifera = `genome_id: "08c83543-c3d9-4a7a-85d8-52f75d61aab0", variant_id: "1:33878:ENSVVVI00100001"`
solanum_lycopersicum = `genome_id: "35a40586-9cb2-4d89-a7db-d00511691d09", variant_id: "1:190:vcZWL7K2"`

2024-01-23 14:48 UTC, likhitha-surapaneni requested changes
Thanks for the PR @nakib103

2024-01-23 14:48 UTC, likhitha-surapaneni commented on common/file_model/variant.py
> +            source, source_info_line = source_header_line.value.split(" ", 1)
The below example is not being parsed as expected
```
variant(
    by_id: {genome_id: "a73357ab-93e7-11ec-a39d-005056b38ce3", variant_id: "1A:61539:Cadenza1158.chr1A.61539"}
  ) {
    name
    
    primary_source {
      description
      }
}
```
```
'EMS-induced': {'mutation" description': "<a href='http://plants.ensembl.org/Triticum_aestivum/Info/Annotation/#variation'>EMS-induced mutations</a> from sequenced wheat TILLING populations. Seeds can be ordered from <a href='https://www.seedstor.ac.uk/shopping-cart-tilling.php'>UK SeedStor</a> or <a href='http://dubcovskylab.ucdavis.edu/wheat-tilling'>US Dubcovsky lab</a>. Line identifier is variant name up to dot (e.g Kronos3128)."}
```

2024-02-05 10:09 UTC, nakib103 commented on common/file_model/variant.py
> +            source, source_info_line = source_header_line.value.split(" ", 1)
Thanks @likhitha-surapaneni , updated!

2024-02-06 13:20 UTC, likhitha-surapaneni commented on common/file_model/variant.py
> +            source, source_info_line = source_header_line.value.split(" ", 1)
Hi @nakib103, looks good to me. Thank you.
The description for this has html code, probably something to communicate to the client?

2024-02-06 13:20 UTC, likhitha-surapaneni approved these changes

2024-02-06 14:31 UTC, merged