Bug fix to returning empty ref allele population frequency
Ensembl/ensembl-hypsipyle pull request #33
Opened 2024-02-08 12:42 UTC by likhitha-surapaneni

- [ ] Test examples 
- [ ] Return allele_frequency as exponential value

2024-02-12 11:16 UTC, likhitha-surapaneni commented
Hi, I see an issue in returning exponent notation for `allele_frequency` on the api side. Currently, this is returning `allele_frequency` as `str`.  I am wondering if it can be done by retaining the `float type` and if this is something to be done on the api side/client side. Let me know your comments.

2024-02-12 11:32 UTC, azangru commented
>  I see an issue in returning exponent notation for allele_frequency on the api side. Currently, this is returning allele_frequency as str. I am wondering if it can be done by retaining the float type and if this is something to be done on the api side/client side.

I am torn between the two options. There are good reasons to pick either. On the one hand, it is better when a number is a number rather than a string; and it is quite reasonable to expect that all the formatting operations are done on the client side. On the other hand, it is also nice to just listen to the backend, and to display whatever it sends. I am slightly leaning towards doing this on the client; but can be convinced otherwise.

2024-02-12 12:49 UTC, nakib103 commented
I also inclined to do this formatting on the client side. Also thinking of external users - I would assume they would want it to be `float` and do their own formatting if need be, instead of getting a formatted string from our api. It is not a big difference but slightly better approach.

2024-02-13 10:30 UTC, nakib103 requested changes

2024-02-13 10:30 UTC, nakib103 commented on common/file_model/variant.py
> +                        if pop_name == pop_freq["population_name"] and pop_freq["allele_frequency"] is not None:
It is just a comment and not need resolving now - we can populate `by_populations` with alt alleles frequencies just by going through the pop_freqs instead of three loops. There might not be much performance improvement (if any), but we can re-visit this concept later if need be.

2024-02-20 15:56 UTC, likhitha-surapaneni commented on common/file_model/variant.py
> +                        if pop_name == pop_freq["population_name"] and pop_freq["allele_frequency"] is not None:
Hi @nakib103 , I tried refactoring the code a bit to remove redundant looping, I see only a slight improvement in time. Can you please check and let me know what you think?

2024-02-21 13:14 UTC, nakib103 commented on common/file_model/variant.py
> +                        if pop_name == pop_freq["population_name"] and pop_freq["allele_frequency"] is not None:
I have getting `~3.5s` on that specific variant, so that's a good improvement. Thanks @likhitha-surapaneni

2024-02-21 13:17 UTC, merged