Updating Predicted Molecular Consequences for EV
Ensembl/ensembl-hypsipyle pull request #36
Opened 2024-02-20 13:40 UTC by likhitha-surapaneni

Ticket: [ENSVAR-6169](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6169)

- [ ] Populate `prediction_result->classification` instead of `prediction_result->result`
- [ ] Parse `variant_relative_location->relation` correctly
- [ ] Test examples

2024-03-01 20:45 UTC, nakib103 requested changes

2024-03-01 20:45 UTC, nakib103 commented on common/file_model/variant_allele.py
> +        if len(alt) > len(self.reference_sequence):
From how VEP create the minimised allele in [CSQ](https://github.com/Ensembl/ensembl-vep/blob/a9c9ffde86368006d348ec1b31163cc54b17e187/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm#L299) we can probably implement this function only by this logic -

```
if self.reference_sequence[0] == alt[0]:
            minimised_allele_string = alt[1:] if len(alt) > 1 else "-"
        return minimised_allele_string
```

With current logic a variant that does not work is - `1:230710046:rs878890662`

2024-03-06 09:58 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +                if cons in ["downstream_gene_variant", "upstream_gene_variant", "intergenic_variant", "regulatory_region_variant"]:
Added this for now, will revisit this when modelling regulatory/motif features

2024-03-06 09:59 UTC, likhitha-surapaneni commented on common/file_model/variant_allele.py
> +        if len(alt) > len(self.reference_sequence):
Thanks @nakib103 , fixed it

2024-03-06 11:45 UTC, nakib103 approved these changes
Looks good. Thanks Likhitha.

2024-03-06 11:45 UTC, merged