Examples for predicted molecular consequences
Ensembl/ensembl-hypsipyle pull request #37
Opened 2024-02-21 13:49 UTC by likhitha-surapaneni

Example list:

- [ ]  1:230710048:rs699 (bi-allelic snp)
- [ ]  13:32379902:rs202155613 (multi-allelic snp)
- [ ]  13:57932508:rs71197234 (insertion with upstream/downstream variants)
- [ ]  21:45988447:rs1312342906(insertion with intron variant)
- [ ] deletion
- [ ] indel
- [ ] substitution

2024-02-21 13:52 UTC, azangru commented on examples/predicted_molecular_consequences/rs202155613.json
> +                  "accession_id": "missense_variant"
Same as above — this should be exposed to the client via the `value` field.

2024-02-21 14:07 UTC, azangru commented on examples/predicted_molecular_consequences/rs71197234.json
> +{
This json isn't particularly interesting as an example; it doesn't have any predicted molecular consequences.

2024-02-21 14:08 UTC, azangru commented on examples/predicted_molecular_consequences/query.graphql
> +          accession_id
value

2024-02-21 14:08 UTC, azangru commented on examples/predicted_molecular_consequences/query.graphql
> +          accession_id
value

2024-02-21 14:13 UTC, azangru commented
Could you also include variant types other than SNV and insertion?

Deletion and substitution?

2024-02-21 14:22 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/rs71197234.json
> +{
Hi @azangru , this was an example to show that we are filtering out data for a set of consequences (downstream/upstream). It was also an example to compare speeds when the array is empty (more relevant for API speed improvements)

However, I agree that there needs to be an insertion example with coding sequences. I will add them along with deletion, indel and substitution examples.

2024-02-21 15:53 UTC, likhitha-surapaneni commented
> Could you also include variant types other than SNV and insertion?
> 
> Deletion and substitution?

Hi @azangru, I have added an example for insertion, deletion, indel and substitution.

2024-02-21 17:03 UTC, azangru commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                  "end": 522,
Is this correct? What are we using as a location here? Why would a deletion of 3 nucleotides have an end coordinate that is the same as the start?

2024-02-21 17:04 UTC, azangru commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                  "end": 13,
Same question as for cDNA.

It might also be worth including an example of a deletion where a different number of nucleotides than 3 are lost, and see how this is reflected in the CDS.

2024-02-21 17:07 UTC, azangru commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                "allele_name": "-",
What does this field mean, and why is it a "-"?

2024-02-21 17:09 UTC, azangru commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                  "ref_sequence": "CAAG",
cDNA includes the anchor base?

What happens if anchor base is the last base of an intron and is spliced out?

2024-02-21 17:14 UTC, azangru commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                  "alt_sequence": "-"
I am confused: you included the anchor base in the reference sequence, but not in the alt.

2024-02-21 17:15 UTC, azangru commented on examples/predicted_molecular_consequences/1:924510:rs1405511870.json
> +                  "ref_sequence": "G",
How does the anchor base behave for cDNA in insertions?

2024-02-21 17:17 UTC, azangru commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                    "value": "inframe_deletion"
Could you also give examples of an insertion and a deletion that are not in-frame?

2024-02-22 11:02 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                  "end": 522,
Hi @azangru , this is a bug in the API, I will update the examples accordingly

2024-02-22 11:04 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                "allele_name": "-",
This is the allele_name derived from the data file.

2024-02-22 11:12 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                  "ref_sequence": "CAAG",
cDNA should not include the anchor base, in my opinion. I will check with the team and make fixes to the API to output the correct and consistent (include/exclude in both reference and alternate sequences) result.

2024-02-22 11:33 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +            "predicted_molecular_consequences": []
Reference alleles are not variants, so I would not expect variant consequences. Same goes for SIFT/Polyphen scores as they are calculated based on amino acid change

2024-02-22 11:48 UTC, azangru commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                "allele_name": "-",
But doesn't the api say, a couple of lines earlier, that the name of the allele is `1:924443:CAAG:C`?

2024-02-22 12:48 UTC, nakib103 requested changes

2024-02-22 12:48 UTC, nakib103 commented on examples/predicted_molecular_consequences/1:966542:rs1642984838.json
> +                "allele_name": "AA",
We are also not modeling `MoitifFeature` in current VDM. Should we remove it for clarity?

2024-02-22 13:17 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                "allele_name": "-",
This field is coming from the VCF columns: `1	924443	rs1449840505	CAAG	C	.	.	SOURCE=dbSNP;CSQ=-|upstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|`

In this, the first column in`CSQ` is the allele_name. So here it is "-". I am not completely sure how we plan to use it. Moreover it also seems redundant to name of the allele except that it is raw string from  the data file. This may be need further clarification from the [VDM](https://github.com/Ensembl/ensembl-vdm-docs/blob/b7f44a82bf9be00f71bbe8c7b1078b9846b036a5/src/docs/predicted_molecular_consequence.md) side.

2024-02-22 13:19 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:924443:rs1449840505.json
> +                  "alt_sequence": "-"
The updated example removes the anchor base from both the sequences

2024-02-22 14:06 UTC, azangru commented on examples/predicted_molecular_consequences/1:924510:rs1405511870.json
> +                  "ref_sequence": "G",
>  I wonder what would be the best representation in the web view - or, another option is we could just remove the small letters alleles there from the API and return as -/CGCTGC

We aren't going to display the sequence for MVP; but originally, Andrea's idea was that only the exact affected sequence, not the codons, gets displayed (example for SNV below):

![image](https://github.com/Ensembl/ensembl-hypsipyle/assets/6834224/0138d940-36db-4f66-92d4-8dcfd052bec7)

I have no idea, by the way, how the above would work with insertions. It is showing the reference sequence, and marking something within it. Whether we were supposed to show the anchor tag, or insert the sequence, as Andrea imagines here for an insertion, I do not know:

![image](https://github.com/Ensembl/ensembl-hypsipyle/assets/6834224/91df1015-ddb0-4a55-8e8f-82d270c46c3e)

I don't know how deeply this has been thought through.

2024-02-22 14:16 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:69456:rs1163254557.json
> +                  "ref_sequence": "-",
Reference sequence returned from VEP does not contain anchoring amino acid unlike in some other cases

2024-02-22 14:21 UTC, azangru commented on examples/predicted_molecular_consequences/1:69456:rs1163254557.json
> +                  "length": 2,
Ugh, insertions are confusing! You represent length differently in the genomic context:

```
  "data": {
    "variant": {
      "name": "rs1163254557",
      "slice": {
        "location": {
          "start": 69456,
          "end": 69457,
          "length": 0
        }
      },
      "alleles": [
        {
          "allele_type": {
            "value": "insertion"
          },
          "slice": {
            "location": {
              "start": 69456,
              "end": 69457,
              "length": 0
            }
          }
        },
        {
          "allele_type": {
            "value": "biological_region"
          },
          "slice": {
            "location": {
              "start": 69456,
              "end": 69456,
              "length": 1
            }
          }
        }
      ]
    }
  },
```

2024-02-22 14:28 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:69456:rs1163254557.json
> +                  "length": 2,
This inconsistency does not look good, I agree. Currently the length for variant_relative_location follows CDM's [relative_location](https://github.com/Ensembl/ensembl-cdm-docs/blob/565985f0c9ad0ffb9180fe8371e76eee4f3ea9c0/src/docs/relative_location.md?plain=1#L9)

2024-02-22 14:29 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:966542:rs1642984838.json
> +                "allele_name": "AA",
Removed MotifFeature for now

2024-02-22 18:48 UTC, nakib103 commented on examples/predicted_molecular_consequences/1:69456:rs1163254557.json
> +                  "ref_sequence": "-",
It seems to happen in case of insertion where the alleles are inserted between two existing codon irrespective of number of alleles inserted, e.g - `1 69456 . C CG` will give `-/X (-/G)` and `1 69454 . C CG` will give `P/RX (ccc/cGcc)`.

For deletion same happens if existing codons are deleted, e.g. - `1 69456 . CCTA C` will give `L/- (CTA/-)`. 

It makes sense as surrounding codon bases are not important in these cases.

2024-02-22 19:03 UTC, nakib103 commented on examples/predicted_molecular_consequences/1:924510:rs1405511870.json
> +                  "ref_sequence": "G",
Only showing the exact affected sequence makes sense. And, the position given is based on the change in exact sequence too. For example here the cds location `79-80` denotes the position of of (first) `g` and `c` in the altered cds sequence `gCGCTGCcg`, so we know `CGCTGC` is inserted after cds position `79`.

2024-02-22 19:10 UTC, nakib103 commented on examples/predicted_molecular_consequences/1:686625:rs1239584546.json
> +                  "ref_sequence": "-",
Hi @likhitha-surapaneni, how are we getting the cdna sequence here? It seems different from cds and rather coming from the genomic sequence (forward strand). 

In case, we are calculating based on genomic sequence would not it become problematic if there is a overlap with intron?

2024-02-29 11:38 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:686625:rs1239584546.json
> +                  "ref_sequence": "-",
This is a good point. The sequence needs to be handled case by case. 

- When cds sequences are available, cdna sequences can be parsed from cds sequences. 
- When cds is partially available or not available, cdna may need to be parsed from genomic sequence by taking strand into consideration

2024-02-29 11:41 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:69456:rs1163254557.json
> +                  "length": 2,
Updated length to be 0 when variant allele is insertion

2024-02-29 13:57 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:69469:rs1350212330.json
> +                  "length": 5,
Currently, `slice` returns 
```
"name": "1:69469:ACAATT:A",
          "slice": {
            "location": {
              "start": 69469,
              "end": 69474,
              "length": 6
            }
          },
```

`variant_alele->slice->location->length` includes the anchoring base while computing length, how do we want to handle it for cdna, cds and protein? @seh @jamie-m-a @nakib103

2024-03-01 10:13 UTC, nakib103 requested changes

2024-03-01 10:13 UTC, nakib103 commented on examples/predicted_molecular_consequences/1:686625:rs1239584546.json
> +                  "ref_sequence": "-",
Hi @likhitha-surapaneni,

Here the cdna sequence is `G` which is in the forward strand. I think it should be `C` - same as cds? 
Also, are we going to trim of the small letter bases for the surrounding bases? I still think it is better idea to do it in the web client side.

For the second point, one example is `rs1639596575` where cds sequence is not available and we are not trying to attempt to form the cdna either. I think that is the sensible for now.

2024-03-01 13:42 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:686625:rs1239584546.json
> +                  "ref_sequence": "-",
Hi @nakib103 , I fixed the incorrect cdna sequence. It should be `C` with the latest code.
For now, I trimmed it to align with the proposed design, however I will address this in the existing ticket : [ENSVAR-6239](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6239)

2024-03-01 13:55 UTC, likhitha-surapaneni commented on examples/predicted_molecular_consequences/1:69456:rs1163254557.json
> +                  "ref_sequence": "-",
This makes sense to me, thanks @nakib103

2024-03-01 14:23 UTC, azangru commented on examples/predicted_molecular_consequences/1:686625:rs1239584546.json
> +                  "ref_sequence": "-",
> For now, I trimmed it to align with the proposed design

_(not a blocker)_ Please check what you will want to show for VEP. I think I heard from Sarah that you will likely want to show codons.

2024-03-01 18:50 UTC, nakib103 commented on examples/predicted_molecular_consequences/1:69469:rs1350212330.json
> +                  "length": 5,
It is hard to say without knowing how `length` is going to be used. Here it seems `length = end - start + 1`. For cdna, cds, and protein that should be same except that they would not have anchoring base.

2024-03-01 18:51 UTC, nakib103 approved these changes
cdna/cds sequence may need re-visiting, but everything else is seems correct for MVP purpose.

2024-03-05 11:47 UTC, nakib103 requested changes

2024-03-05 11:47 UTC, nakib103 commented on examples/predicted_molecular_consequences/1:230710048:rs699.json
> +                "alt_sequence": "G"
```suggestion
                "ref_sequence": "T",
                "alt_sequence": "C"
```

and others of these variant would be same.

2024-03-05 13:27 UTC, nakib103 approved these changes
LGTM for MVP requirements!~

2024-03-05 13:28 UTC, merged