Statistics endpoint
Ensembl/ensembl-hypsipyle pull request #41
Opened 2024-03-21 09:42 UTC by likhitha-surapaneni

[ENSVAR-6219](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6219)

2024-03-22 10:43 UTC, azangru commented on common/schemas/query.graphql
> +  statistics(by_id: IdInput): VariantStatistics
this should probably be called `variant_statistics`?

2024-03-23 15:17 UTC, azangru commented on common/schemas/variant_statistics.graphql
> +  RAF: [VariantAlleleStatisticsFloat]
Ah.

Could we think how to make the names of these fields more readable?

2024-03-25 11:56 UTC, nakib103 requested changes

2024-03-25 11:56 UTC, nakib103 commented on graphql_service/resolver/variant_model.py
> +        raise VariantNotFoundError(by_id["variant_id"])
This check should be on variant and before calling `get_statistics()`. Otherwise we do not get proper error -

```
'NoneType' object has no attribute 'get_statistics'
```

2024-03-25 11:56 UTC, nakib103 commented on examples/variant_statistics/1:230702369:rs11568046.json
It seems to be an empty file.

2024-03-25 11:56 UTC, nakib103 commented on common/file_model/variant.py
> +            rep_pop_allele_frequency.append({"allele_name": self.ref, "number": 1-sum(self.info["RAF"])})
some allele frequency can be `.` and returned as `None` by the vcf reader. We should consider that. Re-produce error with variant - `13:32379902:rs202155613`

2024-03-25 13:38 UTC, nakib103 requested changes

2024-03-25 13:38 UTC, nakib103 commented on common/file_model/variant.py
> +        rep_pop_allele_frequency = [{"allele_name": minimise_allele(i, self.ref), "number": j}  for i,j in zip(alleles, self.info["RAF"])] if "RAF" in self.info else None
1. same - some alleles can have `None` values. The output for is like this `13:32379902:rs202155613` - 
```
"RAF": [
        null,
        {
          "allele_name": "G",
          "number": 0.0000401777
        },
        null
...
```

Should we consider removing the `null`

2. Also, should we round up the decimal position for the frequency as we are doing for the main endpoints?

2024-03-25 13:45 UTC, nakib103 commented
Hi @azangru,

The order of the population in the EV are currently as follows - 
 1. 1000 Genomes 2. gnomAD genomes 3. gnomAD exomes
![image](https://github.com/Ensembl/ensembl-hypsipyle/assets/12125986/198fe440-4518-440a-8fba-ec362fa38b2d)

How this order is derived currently? The **RAF** or the representative population allele frequency we are providing here in the statistics endpoint and which should be shown in the lozenge are from gnomAD. 
<img width="1098" alt="image" src="https://github.com/Ensembl/ensembl-hypsipyle/assets/12125986/0187d861-cdfe-4fac-9933-aa47f50845de">

So, it might be better to update the order like this - 1. gnomAD genomes 2. gnomAD exomes 3. 1000 Genomes

2024-03-26 09:59 UTC, nakib103 requested changes

2024-03-26 10:28 UTC, likhitha-surapaneni commented on common/file_model/populations.json
> +    ],
If populations endpoint is used, `population_metadata.json` needs to be corrected. Updated both the files to be consistent.

Updated the order as per the RAF in the files, thank you @nakib103

2024-03-26 10:45 UTC, nakib103 requested changes

2024-03-26 10:45 UTC, nakib103 commented on common/file_model/variant.py
> +            rep_pop_allele_frequency.append({"allele_name": self.ref, "number": float('%.3g' % float(1-sum(filter(None,self.info["RAF"]))))})
Another thing I noticed that with `%0.3g` we sometimes get a bit confusing result. For `13:32379902:rs202155613` it gives `G:0.0000402` and `C:1`. It feels like total frequency is > 1. 

We can use `%0.3f` instead, it gives fixed point floating number and rounds up the values like `0.0000402` to `0.0`

2024-03-26 10:48 UTC, likhitha-surapaneni commented on common/file_model/variant.py
> +            rep_pop_allele_frequency.append({"allele_name": self.ref, "number": float('%.3g' % float(1-sum(filter(None,self.info["RAF"]))))})
@nakib103 , I see what you mean but rounding off extremely small frequencies to 0.0 also seems like we are not reporting rare frequencies accurately. Let me test this further.

2024-03-26 14:55 UTC, nakib103 commented on common/file_model/variant.py
> +            rep_pop_allele_frequency.append({"allele_name": self.ref, "number": float('%.3g' % float(1-sum(filter(None,self.info["RAF"]))))})
Yeah, it is a decision between cleaner and accurate presentation. As we, have decided to have a certain number of field after the decimal point we need to deal with some inaccuracy - it makes a bad case for rare variant I understand. Another option is to use scientific notation but might be a bit late for MVP ...

2024-03-27 11:37 UTC, likhitha-surapaneni commented on common/file_model/variant.py
> +            rep_pop_allele_frequency.append({"allele_name": self.ref, "number": float('%.3g' % float(1-sum(filter(None,self.info["RAF"]))))})
Hi @nakib103 , I made some changes in how we are handling precision for frequency, please let me know if you find any example that breaks the updated logic

2024-03-27 12:04 UTC, nakib103 commented on common/file_model/variant.py
> +            rep_pop_allele_frequency.append({"allele_name": self.ref, "number": float('%.3g' % float(1-sum(filter(None,self.info["RAF"]))))})
Hi Likhitha,
The allele `G` still gives `0.0000402` but `C` changed to `0.9999598` which is a good thing as we now have total 1. But do we want them to be round upto 3 decimal places?

The reason we are getting this many digits after decimal, as far as I understand, is that - with the logic of [general (g)](https://python-reference.readthedocs.io/en/latest/docs/functions/format.html) format the number is represented as exponential and thus retaining the original precision.

2024-03-27 15:30 UTC, likhitha-surapaneni commented on common/file_model/variant.py
> +            rep_pop_allele_frequency.append({"allele_name": self.ref, "number": float('%.3g' % float(1-sum(filter(None,self.info["RAF"]))))})
The fix still does not follow the convention of 3 significant figures for reference frequency.

[Current site](http://www.ensembl.org/Homo_sapiens/Variation/Population?db=core;r=13:32379402-32380402;v=rs202155613;vdb=variation;vf=814723714) shows 
ref: 1.000  , alt: 4.018e-05 

I agree that the question comes down to cleaner vs accurate representation. We need to also understand if the pie charts on the frequency pages require the sum of frequencies to be 1.

The problem may still persist with scientific notation as we may have to restrict the number of digits in the coeffiecient:

Scientific notation without restriction :
ref: “4.017770e-05”, alt:“9.999598e-01"

Scientific notation restricting coefficient to two decimal points:
ref: “4.02e-05”, alt: “1.00e+00"

2024-04-02 13:45 UTC, azangru commented on common/schemas/variant_statistics.graphql
> +  representative_population_allele_frequency: [VariantAlleleStatisticsFloat]!
frequency -> frequencies? Given that it's an array?

2024-04-02 13:54 UTC, azangru commented
I am curious about the proposed schema for the variant statstics query:

```
  count_transcript_consequences: Int!
  count_overlapped_genes: Int!
  count_regulatory_consequences: Int!
  counts_variant_phenotypes: [VariantAlleleStatisticsInt]!
  counts_gene_phenotypes: [VariantAlleleStatisticsInt]!
  count_citations: Int!
  representative_population_allele_frequency: [VariantAlleleStatisticsFloat]!
```

This suggests that some of these fields are not going to be allele-specific. For example, that all alleles of a variant will have the same number of transcript consequences. Is this correct? A reference allele doesn't have any transcript consequences at all; but among alternative alleles, can't they have a different count of transcript consequences if e.g. they have different lengths?

Also, you are currently identifying alleles using allele names (SPDI's). Remember we mentioned earlier that it would be helpful for the website if alleles were identified by something short and unique within a variant? Currently, the website uses the indexes of alleles in the array of alleles to identify the allele. Could you revive this topic in the Variation team and see if you could come up with an identifier to put in allele.id field that we can use?

2024-04-02 15:33 UTC, nakib103 approved these changes
We might need to re-visit whether to put some fields in variant allele level instead of variant (could be an update). 
Other changes working fine.

2024-04-03 13:40 UTC, likhitha-surapaneni commented
> Also, you are currently identifying alleles using allele names (SPDI's). Remember we mentioned earlier that it would be helpful for the website if alleles were identified by something short and unique within a variant? Currently, the website uses the indexes of alleles in the array of alleles to identify the allele. Could you revive this topic in the Variation team and see if you could come up with an identifier to put in allele.id field that we can use?

Hi @azangru, does it help if we maintain the same order of alleles always? I am trying to understand the use case better. Is this allele id useful in matching alleles for the stats endpoint?

2024-04-03 14:00 UTC, likhitha-surapaneni commented
> This suggests that some of these fields are not going to be allele-specific. For example, that all alleles of a variant will have the same number of transcript consequences. Is this correct? A reference allele doesn't have any transcript consequences at all; but among alternative alleles, can't they have a different count of transcript consequences if e.g. they have different lengths?

I agree with reporting the count for each variant allele as the design requires reporting at a variant allele level. While the data would only be available after the next run, we are making changes to the API to return the intended schema for fields which were previously reported at variant level (however shows the same value for all the variant alleles until the data is ready). The counts for reference allele are 0 for transcript_consequences, regulatory_consequences, citations, overlapped_genes. Would it be better if the API explicitly reported that for reference allele?

2024-04-03 15:06 UTC, azangru commented
> The counts for reference allele are 0 for transcript_consequences, regulatory_consequences, citations, overlapped_genes. Would it be better if the API explicitly reported that for reference allele?

If these counts are allele-specific (e.g. one alt allele may have counts that are different from other alt allele), then yes, I think the right thing would be to also include the zeros for the reference allele.

It these counts are variant-specific (i.e. the same across all alt alleles and only 0 for reference), then it is worth having two different `statistics` resolvers — one at the variant level, with variant-specific statistics data, and one at the allele level, with allele-specific statistics.

Looking at the [design mockup](https://xd.adobe.com/view/573e7994-6561-412f-84f0-b34c0d38761e-026d/screen/4d373ade-7d75-4e85-86c7-ac489855c4cf), it seems like it distinguishes variant statistics from allele statistics (reference allele still shows non-zero values under the navigation buttons in the mockup); but I do not know the specifics of your data. I'll put this on the agenda for discussion.

2024-05-03 09:02 UTC, likhitha-surapaneni commented
Superseded by [https://github.com/Ensembl/ensembl-hypsipyle/pull/44](https://github.com/Ensembl/ensembl-hypsipyle/pull/44)

2024-05-03 09:02 UTC, closed without merging